"""Per-segment readiness advice computed from a use-case record and a case index."""

# evorthon-component: readiness
from .projection import (
    AVAILABILITY_EVIDENCE,
    DATASET_FACT_KINDS,
    DIGEST_ALGORITHM,
    DIGEST_SIZE_BYTES,
    GAP_OWNER_ROLES,
    GAP_TITLE_ACTIONS,
    READINESS_PROJECTION_FORM,
    SYNTHETIC_FILLABLE,
    CaseDataset,
    CaseExpectedOutput,
    CaseFacts,
    FactEvidence,
    FactKind,
    OpenCondition,
    ReadinessError,
    ReadinessFact,
    ReadinessGap,
    ReadinessProjection,
    RefusalReason,
    SegmentReadiness,
    SegmentState,
    project_readiness,
    projection_digest,
    render_projection,
    suggested_item_title,
)

__all__ = [
    "AVAILABILITY_EVIDENCE",
    "CaseDataset",
    "CaseExpectedOutput",
    "CaseFacts",
    "DATASET_FACT_KINDS",
    "DIGEST_ALGORITHM",
    "DIGEST_SIZE_BYTES",
    "FactEvidence",
    "FactKind",
    "GAP_OWNER_ROLES",
    "GAP_TITLE_ACTIONS",
    "OpenCondition",
    "READINESS_PROJECTION_FORM",
    "ReadinessError",
    "ReadinessFact",
    "ReadinessGap",
    "ReadinessProjection",
    "RefusalReason",
    "SYNTHETIC_FILLABLE",
    "SegmentReadiness",
    "SegmentState",
    "project_readiness",
    "projection_digest",
    "render_projection",
    "suggested_item_title",
]
