"""Verification orchestration over portable contracts and ports."""

# evorthon-component: verification_workflows
from .adviser import (
    ADVICE_VERSION,
    ADVISER_REPLY_FORM,
    ADVISER_ROUTE,
    ADVISER_WORKFLOW_FORM,
    AdviserHypothesis,
    AdviserRefusalReason,
    AdviserRefused,
    AdviserReply,
    AdviserRoute,
    CONTRADICTING_IDENTITIES_FIELD,
    DiagnosticAdviceOutcome,
    SUPPORTING_IDENTITIES_FIELD,
    advise_on_fault,
    adviser_call_fields,
    build_adviser_call,
    read_adviser_reply,
)
from .delivery_contract import (
    BLOCKING_FAMILIES,
    ClauseExecution,
    ClauseFinding,
    ClauseObservation,
    ContractFindingKind,
    ContractRefusalReason,
    ContractRefused,
    DELIVERY_CONTRACT_FORM,
    DIMENSION_BY_FAMILY,
    DeliveryContractOutcome,
    EVALUATOR_BY_FAMILY,
    EXECUTED_RULE_OPERATORS,
    EvidenceBasis,
    ExecutedObservation,
    OWNER_BASES,
    PRESENTED_BASES,
    PresentedObservation,
    evaluate_conformance,
    evaluate_delivery_integrity,
    evaluate_invariant,
    evaluate_operational_evidence,
    evaluate_parity,
    execute_delivery_contract,
)
from .diagnosis import (
    DIAGNOSIS_WORKFLOW_FORM,
    DiagnosisOutcome,
    diagnose_failed_output,
)
# The input types reconcile_run takes. They are published here so a caller of
# this layer can name what the function requires without reaching past it.
from evorthon_data.verification.core.reconciliation import (
    CandidateObservation,
    ExpectedMaterial,
    ReconciliationRefused,
)
# The refusal types the engines behind this layer raise, published for the same
# reason: a caller reports exactly the refusals it named and nothing else.
from evorthon_data.verification.core.canonical import CanonicalisationRefusal
from evorthon_data.verification.core.fault import FaultRefused
from evorthon_data.verification.core.localisation import LocalisationRefused
from evorthon_data.verification.ports.contracts import PortRefusal
from .intake import (
    AcceptedIntake,
    ConfirmedEvidence,
    INTAKE_AUTHORITY_ID,
    INTAKE_RECEIPT_VERSION,
    INTAKE_WORKFLOW_FORM,
    IntakeRefusal,
    IntakeRefusalReason,
    IntakeRefused,
    IntakeReport,
    RECEIPT_SUBJECT_BY_ROLE,
    confirm_intake_case,
    declared_evidence,
    frozen_case_facts,
    inspect_intake,
    intake_case,
)
from .reconciliation import (
    RECONCILIATION_RESULT_VERSION,
    REPEAT_RUN_VERSION,
    ReconciliationOutcome,
    reconcile_run,
)
from .remediation import (
    APPROVING_DISPOSITIONS,
    DECISION_REMAINDER,
    DecidingActor,
    EDITED_ADVICE_MARKER,
    HUMAN_DISPOSITIONS,
    HumanDisposition,
    REMEDIATION_DECISION_VERSION,
    REMEDIATION_RERUN_FORM,
    REMEDIATION_WORKFLOW_FORM,
    REMEDIATION_WORK_VERSION,
    RemediationActorKind,
    RemediationOutcome,
    RemediationRefusalReason,
    RemediationRefused,
    RemediationRerun,
    WORK_REMAINDER,
    record_remediation_decision,
    rerun_corrected_case,
)
from .replay import (
    REPLAY_WORKFLOW_FORM,
    ReplayExplanation,
    ReplayRefusalReason,
    ReplayRefused,
    ReplayReport,
    isolated_facts,
    replay_checkpoint,
    replay_localisation,
)

__all__ = [
    "ADVICE_VERSION",
    "ADVISER_REPLY_FORM",
    "ADVISER_ROUTE",
    "ADVISER_WORKFLOW_FORM",
    "APPROVING_DISPOSITIONS",
    "AcceptedIntake",
    "AdviserHypothesis",
    "AdviserRefusalReason",
    "AdviserRefused",
    "AdviserReply",
    "AdviserRoute",
    "BLOCKING_FAMILIES",
    "CONTRADICTING_IDENTITIES_FIELD",
    "CandidateObservation",
    "CanonicalisationRefusal",
    "ClauseExecution",
    "ClauseFinding",
    "ClauseObservation",
    "ConfirmedEvidence",
    "ContractFindingKind",
    "ContractRefusalReason",
    "ContractRefused",
    "DECISION_REMAINDER",
    "DELIVERY_CONTRACT_FORM",
    "DIAGNOSIS_WORKFLOW_FORM",
    "DIMENSION_BY_FAMILY",
    "DecidingActor",
    "DeliveryContractOutcome",
    "DiagnosisOutcome",
    "DiagnosticAdviceOutcome",
    "EDITED_ADVICE_MARKER",
    "EVALUATOR_BY_FAMILY",
    "EXECUTED_RULE_OPERATORS",
    "EvidenceBasis",
    "ExecutedObservation",
    "ExpectedMaterial",
    "FaultRefused",
    "HUMAN_DISPOSITIONS",
    "HumanDisposition",
    "INTAKE_AUTHORITY_ID",
    "INTAKE_RECEIPT_VERSION",
    "INTAKE_WORKFLOW_FORM",
    "IntakeRefusal",
    "IntakeRefusalReason",
    "IntakeRefused",
    "IntakeReport",
    "LocalisationRefused",
    "OWNER_BASES",
    "PRESENTED_BASES",
    "PortRefusal",
    "PresentedObservation",
    "RECEIPT_SUBJECT_BY_ROLE",
    "RECONCILIATION_RESULT_VERSION",
    "REMEDIATION_DECISION_VERSION",
    "REMEDIATION_RERUN_FORM",
    "REMEDIATION_WORKFLOW_FORM",
    "REMEDIATION_WORK_VERSION",
    "REPEAT_RUN_VERSION",
    "REPLAY_WORKFLOW_FORM",
    "ReconciliationOutcome",
    "ReconciliationRefused",
    "RemediationActorKind",
    "RemediationOutcome",
    "RemediationRefusalReason",
    "RemediationRefused",
    "RemediationRerun",
    "ReplayExplanation",
    "ReplayRefusalReason",
    "ReplayRefused",
    "ReplayReport",
    "SUPPORTING_IDENTITIES_FIELD",
    "WORK_REMAINDER",
    "advise_on_fault",
    "adviser_call_fields",
    "build_adviser_call",
    "confirm_intake_case",
    "declared_evidence",
    "diagnose_failed_output",
    "evaluate_conformance",
    "evaluate_delivery_integrity",
    "evaluate_invariant",
    "evaluate_operational_evidence",
    "evaluate_parity",
    "execute_delivery_contract",
    "frozen_case_facts",
    "inspect_intake",
    "intake_case",
    "isolated_facts",
    "read_adviser_reply",
    "reconcile_run",
    "record_remediation_decision",
    "replay_checkpoint",
    "replay_localisation",
    "rerun_corrected_case",
]
