"""Portable deterministic verification semantics."""

# evorthon-component: verification_core
from .canonical import (
    CANONICAL_RECORD_FORM,
    CANONICAL_ROW_STREAM_FORM,
    CanonicalisationRefusal,
    DIGEST_PREFIX,
    HASH_ALGORITHM,
    HASH_DIGEST_SIZE_BYTES,
    RECORD_TEXT_NORMALISATION,
    RefusalReason,
    SUPPORTED_NON_FINITE_NUMBER_POLICIES,
    SUPPORTED_NULL_REPRESENTATIONS,
    SUPPORTED_SIGNED_ZERO_REPRESENTATIONS,
    SUPPORTED_TIMEZONES,
    SUPPORTED_UNICODE_NORMALISATIONS,
    TIE_BREAKER_DIRECTION,
    TIE_BREAKER_NULL_PLACEMENT,
    TIMESTAMP_PRECISION_DIGITS,
    canonical_digest,
    canonical_record_bytes,
    canonical_row_stream,
    case_digest,
    dataset_digest,
    frozen_dataset_digest,
    record_digest,
    result_digest,
)

__all__ = [
    "CANONICAL_RECORD_FORM",
    "CANONICAL_ROW_STREAM_FORM",
    "CanonicalisationRefusal",
    "DIGEST_PREFIX",
    "HASH_ALGORITHM",
    "HASH_DIGEST_SIZE_BYTES",
    "RECORD_TEXT_NORMALISATION",
    "RefusalReason",
    "SUPPORTED_NON_FINITE_NUMBER_POLICIES",
    "SUPPORTED_NULL_REPRESENTATIONS",
    "SUPPORTED_SIGNED_ZERO_REPRESENTATIONS",
    "SUPPORTED_TIMEZONES",
    "SUPPORTED_UNICODE_NORMALISATIONS",
    "TIE_BREAKER_DIRECTION",
    "TIE_BREAKER_NULL_PLACEMENT",
    "TIMESTAMP_PRECISION_DIGITS",
    "canonical_digest",
    "canonical_record_bytes",
    "canonical_row_stream",
    "case_digest",
    "dataset_digest",
    "frozen_dataset_digest",
    "record_digest",
    "result_digest",
]
