"""Fail-closed validation, schemas, and serialization for verification records."""

# evorthon-component: verification_enforcement

from evorthon_data.verification.enforcement.privacy import (
    PACKET_BOUNDS,
    PRIVACY_GATE_FORM,
    GatedFaultPacket,
    PacketBounds,
    PrivacyRefusalKind,
    PrivacyRefusalReason,
    PrivacyRefused,
    gate_fault_packet,
    inspect_fault_packet,
)
from evorthon_data.verification.enforcement.schema import (
    UNKNOWN_FIELD_POLICY,
    UNKNOWN_VERSION_POLICY,
    generate_json_schema,
    generate_serialization_projection,
    schema_projection_drift,
)
from evorthon_data.verification.enforcement.serialization import (
    SerializationError,
    UnknownFieldError,
    UnknownRecordTypeError,
    UnknownSchemaVersionError,
    deserialize_json,
    deserialize_record,
    serialize_json,
    serialize_record,
)
from evorthon_data.verification.enforcement.validation import (
    PolicyChangedAfterObservationError,
    PolicyObservation,
    ValidationIssue,
    ValidationReport,
    VerificationContractError,
    ensure_policy_unchanged,
    inspect_case,
    inspect_verification_record,
    inspect_verification_case,
    observe_policy,
    validate_verification_case,
    validate_case,
    validate_verification_record,
)

__all__ = [
    "GatedFaultPacket",
    "PACKET_BOUNDS",
    "PRIVACY_GATE_FORM",
    "PacketBounds",
    "PolicyChangedAfterObservationError",
    "PolicyObservation",
    "PrivacyRefusalKind",
    "PrivacyRefusalReason",
    "PrivacyRefused",
    "SerializationError",
    "UNKNOWN_FIELD_POLICY",
    "UNKNOWN_VERSION_POLICY",
    "UnknownFieldError",
    "UnknownRecordTypeError",
    "UnknownSchemaVersionError",
    "ValidationIssue",
    "ValidationReport",
    "VerificationContractError",
    "deserialize_json",
    "deserialize_record",
    "ensure_policy_unchanged",
    "gate_fault_packet",
    "generate_json_schema",
    "inspect_fault_packet",
    "generate_serialization_projection",
    "inspect_verification_case",
    "inspect_verification_record",
    "inspect_case",
    "observe_policy",
    "schema_projection_drift",
    "serialize_json",
    "serialize_record",
    "validate_verification_case",
    "validate_case",
    "validate_verification_record",
]
